apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox-file
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      name: busybox
    spec:
      containers:
      - command:
        - powershell.exe
        - -Command
        - sleep 10000;
        image: e2eteam/busybox:1.29
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/file
          name: myfile
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
      - name: myfile
        hostPath:
          path: /var/local/aaa/1.txt
          type: FileOrCreate
