apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox-file-linux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      name: busybox
    spec:
      containers:
      - args:
        - sleep
        - "100000"
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/file
          name: myfile
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: myfile
        hostPath:
          path: /mount_test/1.txt
          type: FileOrCreate
