apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox-smb-subpath-linux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      name: busybox
    spec:
      containers:
      - args:
        - sleep
        - "100000"
        image: radial/busyboxplus:curl
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/smb
          name: smb
          subPath: aa
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: smb
        persistentVolumeClaim:
          claimName: pvc-smb-linux
