apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox-subdir
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      name: busybox
    spec:
      containers:
      - command:
        - powershell.exe
        - -Command
        - sleep 10000;
        image: e2eteam/busybox:1.29
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/dir
          name: mydir
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
      - name: mydir
        hostPath:
          path: '/k'
          type: Directory
