apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-linux
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
    volumeAttributes:
      source: \\172.16.3.132\share
    volumeHandle: linux
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

