apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-linux
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-smb-linux
