apiVersion: v1
data:
  prometheus.yaml: ewogICAgYXBpVmVyc2lvbjogMSwKICAgIGRhdGFzb3VyY2VzOiBbCiAgICAgICAgewogICAgICAgICAgICBhY2Nlc3M6IHByb3h5LAogICAgICAgICAgICBlZGl0YWJsZTogZmFsc2UsCiAgICAgICAgICAgIG5hbWU6IFByb21ldGhldXMsCiAgICAgICAgICAgIG9yZ0lkOiAxLAogICAgICAgICAgICB0eXBlOiBwcm9tZXRoZXVzLAogICAgICAgICAgICB1cmw6IGh0dHA6Ly9wcm9tZXRoZXVzOjkwOTAsCiAgICAgICAgICAgIHZlcnNpb246IDEsCiAgICAgICAgICAgICAgICAgICAgICAgIHJlYWRPbmx5OiBmYWxzZQogICAgICAgIH0KICAgIF0KfQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: grafana-datasources
  namespace: kube-system


