apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-config
  namespace: kube-system
  labels:
    app: ingress-nginx
data:
  ssl-redirect: "false"
  hsts: "false"
  use-gzip: "false"
  enable-underscores-in-headers: "true"
  server-tokens: "false"
  http-redirect-code: "301"


