{
 "title": "K8s Ingress Controller",
 "description": "Ingress-nginx supports a rich collection of prometheus metrics. If you have prometheus and grafana installed on your cluster then prometheus will already be scraping this data due to the scrape annotation on the deployment.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
   },
   {
    "name": "ingress",
    "query": "label_values(nginx_ingress_controller_success{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_namespace=~\"$controller\"}, ingress) "
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_nginx_process_requests_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Modified Config",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{controller_pod=~\"$controller\",controller_class=~\"$controller_class\", controller_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_nginx_process_requests_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) by (controller_class), 0.001)",
     "legendFormat": "{{ controller_class }}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "CPU (cores)" }
   ],
   "targets": [
    {
     "expr": "avg (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])*100) by (controller_class)",
     "legendFormat": "{{ controller_class }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) by (controller_class)",
     "legendFormat": "{{ controller_class }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_nginx_process_write_bytes_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) by (controller_class)",
     "legendFormat": "Received-{{ controller_class }}"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_nginx_process_read_bytes_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) by (controller_class)",
     "legendFormat": "Sent-{{ controller_class }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{kubernetes_pod_name=~\"$controller\",namespace=~\"$namespace\",ingress=~\"$ingress\"}) by (host) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}