{
 "title": "POD History Dashboard",
 "tags": [ "Pod" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_cpu_usage_seconds_total{namespace=~\".+\", container_name!=\"POD\"}, namespace)"
   },
   {
    "name": "podname",
    "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",namespace=~\"$namespace\",pod=~\"$podname\"}[2m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\",image!=\"\",namespace=~\"$namespace\",pod=~\"$podname\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$podname\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}