{
 "title": "K8s Node Exporter Network",
 "description": "Based on https://grafana.com/dashboards/1860 , with some small changes for job naming under kubernetes.",
 "tags": [ "node" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Network traffic Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive drop"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit drop"
    }
   ]
  },
  {
   "title": "Network Traffic Compressed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_compressed_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive compressed"
    },
    {
     "expr": "irate(node_network_transmit_compressed_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit compressed"
    }
   ]
  },
  {
   "title": "Network Traffic Multicast",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_multicast_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive multicast"
    },
    {
     "expr": "irate(node_network_transmit_multicast{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit multicast"
    }
   ]
  },
  {
   "title": "Network Traffic Fifo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_fifo_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive fifo"
    },
    {
     "expr": "irate(node_network_transmit_fifo_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit fifo"
    }
   ]
  },
  {
   "title": "Network Traffic Frame",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_frame_total{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Receive frame"
    },
    {
     "expr": "irate(node_network_transmit_frame{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}} - Transmit frame"
    }
   ]
  },
  {
   "title": "NF Contrack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Entries" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$node:$port\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node:$port\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$node:$port\"}",
       "legendFormat": "TCP_alloc - Allocated sockets"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~\"$node:$port\"}",
       "legendFormat": "TCP_inuse - Tcp sockets currently in use"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=~\"$node:$port\"}",
       "legendFormat": "TCP_mem - Used memory for tcp"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=~\"$node:$port\"}",
       "legendFormat": "TCP_orphan - Orphan sockets"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$node:$port\"}",
       "legendFormat": "TCP_tw - Sockets wating close"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$node:$port\"}",
       "legendFormat": "UDPLITE_inuse - Udplite sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~\"$node:$port\"}",
       "legendFormat": "UDP_inuse - Udp sockets currently in use"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=~\"$node:$port\"}",
       "legendFormat": "UDP_mem - Used memory for udp"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=~\"$node:$port\"}",
       "legendFormat": "Sockets_used - Sockets currently in use"
      }
     ]
    },
    {
     "title": "Sockstat Memory Size",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "TCP_mem_bytes - "
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=~\"$node:$port\"}",
       "legendFormat": "UDP_mem_bytes - "
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "Sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=~\"$node:$port\"}",
       "legendFormat": "FRAG_inuse - Frag sockets currently in use"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=~\"$node:$port\"}",
       "legendFormat": "FRAG_memory - Used memory for frag"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=~\"$node:$port\"}",
       "legendFormat": "RAW_inuse - Raw sockets currently in use"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP Forwarding",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short", "label": "Datagrams" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_Forwarding{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "Forwarding - Ip forwarding"
      }
     ]
    },
    {
     "title": "Netstat IP In / Out Octets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short", "label": "Octects out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InOctets - Received octets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "OutOctets - Sent octets"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short", "label": "Segments out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node:$port\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP Linux MIPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP SynCookie / Challenge",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short", "label": "Counter out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "SyncookiesFailed - Invalid SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "SyncookiesRecv - SYN cookies received"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "SyncookiesSent - SYN cookies sent"
      }
     ]
    },
    {
     "title": "TCP Retrans",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 105 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      }
     ]
    },
    {
     "title": "TCP DROPS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 115 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      }
     ]
    },
    {
     "title": "TCP Issues",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 115 },
     "yaxes": [
      { "format": "short", "label": "Counter" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "UDP In / Out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InDatagrams - Datagrams received"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "OutDatagrams - Datagrams sent"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "NoPorts - Datagrams received on a port with no listener"
      }
     ]
    },
    {
     "title": "UDP Lite Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InErrors - Datagrams that could not be delivered to an application"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Errors 1",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 147 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      }
     ]
    },
    {
     "title": "ICMP In / Out - Messages / Redirects",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 147 },
     "yaxes": [
      { "format": "short", "label": "Messages out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=~\"$node:$port\"}[5m])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      }
     ]
    }
   ]
  }
 ]
}